//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravauxDisciplinaireCFPT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravauxDisciplinaireCFPT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_project_management {
            get {
                object obj = ResourceManager.GetObject("icon_project_management", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAEF_PlanningTPIV2 {
            get {
                object obj = ResourceManager.GetObject("NAEF_PlanningTPIV2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le petit poucet
        ///Un bûcheron et sa femme n&apos;ont plus de quoi nourrir leurs sept garçons. Un soir, alors que les enfants dorment, les parents se résignent, la mort dans l&apos;âme, à les perdre dans la forêt. Heureusement, le plus petit de la fratrie, âgé de sept ans, surnommé Petit Poucet en raison de sa petite taille, espionne la conversation. Prévoyant, il se munit de petits cailloux blancs qu&apos;il laissera tomber un à un derrière afin que lui et ses frères puissent retrouver leur chemin. Le lendemain, le père me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexteNiveau1 {
            get {
                return ResourceManager.GetString("TexteNiveau1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guillaume Tell
        ///Le récit traditionnel
        ///Selon le Livre blanc de Sarnen (1474), « le Tall »1 est un homme honnête qui avait juré avec Stauffacher et d&apos;autres partisans de résister aux seigneurs. À cette époque, sous l&apos;empereur Albert Ier de Habsbourg, les baillis établis par son prédécesseur Rodolphe Ier de Habsbourg se livrent à des exactions. Le 25 juillet 13072, l&apos;un de ces baillis, Hermann Gessler, fait ériger un poteau sur la place des Tilleuls à Altdorf et y accroche son chapeau, obligeant tous les habi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexteNiveau2 {
            get {
                return ResourceManager.GetString("TexteNiveau2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histoire de la suisse
        ///Période glacière et âge de pierre
        ///Glacier de Morteratsch, Grisons, Suisse.
        ///Il y a à peu près deux millions d&apos;années, les températures ont coulé et l&apos;Europe a été couverte par des glaciers presque completément. A Lucerne, en Suisse centrale, l&apos;épaisseur de la glace a atteint autant qu&apos;à peu près 1000 m. Quand la glace a fondu et s&apos;est retirée lentement il y a à peu près 30&apos;000 années, les animaux et les hommes sont arrivés en Europe. Mais le centre de développement culturel est resté [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexteNiveau3 {
            get {
                return ResourceManager.GetString("TexteNiveau3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlemagne
        ///Introduction
        ///Avec la bénédiction du pape, les maires du palais ont usurpé le trône aux derniers Mérovingiens, « les rois fainéants ». Pépin le Bref devenu roi des Francs en 751, parvient à restaurer l&apos;unité du royaume. Avec la reine Bertrade « Berthe au grand pied », la fille du comte de Laon, un puissant seigneur de l&apos;époque, Pépin a deux fils : Charles et Carloman. Très vite l&apos;aîné Charles s&apos;impose et annonce son style, il se fera appeler « le Grand », et deviendra l&apos;un des plus grand souver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexteNiveau4 {
            get {
                return ResourceManager.GetString("TexteNiveau4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histoire de Genève
        ///Introduction
        ///L&apos;histoire de Genève se déroule sur une période de deux mille ans. Mentionnée pour la première fois dans les Commentaires sur la Guerre des Gaules de Jules César, la cité estpassée sous la domination romaine, puis des Burgondes et des Francs avant de devenir un évêché indépendant pendant le Moyen Âge. Avec l&apos;arrivée de Jean Calvin, la ville adopte la Réforme protestante et devient un important centre de diffusion du calvinisme à l&apos;échelle européenne. Son tissu économique se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TexteNiveau5 {
            get {
                return ResourceManager.GetString("TexteNiveau5", resourceCulture);
            }
        }
    }
}
