//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravauxDisciplinaireCFPT.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravauxDisciplinaireCFPT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnCours {
            get {
                object obj = ResourceManager.GetObject("EnCours", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoAPropos {
            get {
                object obj = ResourceManager.GetObject("logoAPropos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ManuelUtilisateur {
            get {
                object obj = ResourceManager.GetObject("ManuelUtilisateur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le petit poucet
        ///Un bûcheron et sa femme n&apos;ont plus de quoi nourrir leurs sept garçons. Un soir, alors que les enfants dorment, les parents se résignent, la mort dans l&apos;âme, à les perdre dans la forêt. Heureusement, le plus petit de la fratrie, âgé de sept ans, surnommé Petit Poucet en raison de sa petite taille, espionne la conversation. Prévoyant, il se munit de petits cailloux blancs qu&apos;il laissera tomber un à un derrière afin que lui et ses frères puissent retrouver leur chemin. Le lendemain, le père me [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TexteNiveau1 {
            get {
                return ResourceManager.GetString("TexteNiveau1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guillaume Tell
        ///Le récit traditionnel
        ///Selon le Livre blanc de Sarnen (1474), « le Tall »1 est un homme honnête qui avait juré avec Stauffacher et d&apos;autres partisans de résister aux seigneurs. À cette époque, sous l&apos;empereur Albert Ier de Habsbourg, les baillis établis par son prédécesseur Rodolphe Ier de Habsbourg se livrent à des exactions. Le 25 juillet 13072, l&apos;un de ces baillis, Hermann Gessler, fait ériger un poteau sur la place des Tilleuls à Altdorf et y accroche son chapeau, obligeant tous les habi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TexteNiveau2 {
            get {
                return ResourceManager.GetString("TexteNiveau2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Histoire de la suisse
        ///Période glacière et âge de pierre
        ///Glacier de Morteratsch, Grisons, Suisse.
        ///Il y a à peu près deux millions d&apos;années, les températures ont coulé et l&apos;Europe a été couverte par des glaciers presque completément. A Lucerne, en Suisse centrale, l&apos;épaisseur de la glace a atteint autant qu&apos;à peu près 1000 m. Quand la glace a fondu et s&apos;est retirée lentement il y a à peu près 30&apos;000 années, les animaux et les hommes sont arrivés en Europe. Mais le centre de développement culturel est resté [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TexteNiveau3 {
            get {
                return ResourceManager.GetString("TexteNiveau3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charlemagne
        ///Introduction
        ///Avec la bénédiction du pape, les maires du palais ont usurpé le trône aux derniers Mérovingiens, « les rois fainéants ». Pépin le Bref devenu roi des Francs en 751, parvient à restaurer l&apos;unité du royaume. Avec la reine Bertrade « Berthe au grand pied », la fille du comte de Laon, un puissant seigneur de l&apos;époque, Pépin a deux fils : Charles et Carloman. Très vite l&apos;aîné Charles s&apos;impose et annonce son style, il se fera appeler « le Grand », et deviendra l&apos;un des plus grand souver [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TexteNiveau4 {
            get {
                return ResourceManager.GetString("TexteNiveau4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Histoire de Genève
        ///Introduction
        ///L&apos;histoire de Genève se déroule sur une période de deux mille ans. Mentionnée pour la première fois dans les Commentaires sur la Guerre des Gaules de Jules César, la cité estpassée sous la domination romaine, puis des Burgondes et des Francs avant de devenir un évêché indépendant pendant le Moyen Âge. Avec l&apos;arrivée de Jean Calvin, la ville adopte la Réforme protestante et devient un important centre de diffusion du calvinisme à l&apos;échelle européenne. Son tissu économique se [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TexteNiveau5 {
            get {
                return ResourceManager.GetString("TexteNiveau5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Travail_fini {
            get {
                object obj = ResourceManager.GetObject("Travail_fini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TravailEnCours {
            get {
                object obj = ResourceManager.GetObject("TravailEnCours", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
